title: Xue Beichen's Personal Website
email: xue.beichen@u.nus.edu
description: "Musings of a young Mathematician and Computer Scientist."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bcc2023.github.io" # the base hostname & protocol for your site, e.g. http://example.com
name: Xue Beichen
github_username: bcc2023

markdown: kramdown
permalink: pretty

theme: minima

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge